# This file created by conda-build 24.3.0
# meta.yaml template originally from:
# C:\b\abs_e46tf0_91g\clone\recipe, last modified Thu May  2 20:31:20 2024
# ------------------------------------------------

package:
  name: zstandard
  version: 0.22.0
source:
  patches:
    - use_system_zstd.patch
  sha256: 8226a33c542bcb54cd6bd0a366067b610b41713b64c9abec1bc4533d69f51e70
  url: https://pypi.io/packages/source/z/zstandard/zstandard-0.22.0.tar.gz
build:
  number: '0'
  script: C:\\b\\abs_e46tf0_91g\\croot\\zstandard_1714678303615\\_h_env\\python.exe
    -m pip install --no-deps --no-build-isolation . -vv
  string: py312h3469f8a_0
requirements:
  build:
    - m2-msys2-runtime 2.5.0.17080.65c939c 3
    - m2-patch 2.7.5 2
    - msys2-conda-epoch 20160418 1
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
  host:
    - bzip2 1.0.8 h2bbff1b_6
    - ca-certificates 2024.3.11 haa95532_0
    - cffi 1.16.0 py312h2bbff1b_1
    - expat 2.6.2 hd77b12b_0
    - libffi 3.4.4 hd77b12b_1
    - lz4-c 1.9.4 h2bbff1b_1
    - openssl 3.0.13 h2bbff1b_1
    - pip 23.3.1 py312haa95532_0
    - pycparser 2.21 pyhd3eb1b0_0
    - python 3.12.3 h1d929f7_0
    - setuptools 68.2.2 py312haa95532_0
    - sqlite 3.45.3 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2024a h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.41.2 py312haa95532_0
    - xz 5.4.6 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_1
    - zstd 1.5.5 hd43e919_1
  run:
    - cffi >=1.11
    - python >=3.12,<3.13.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
    - zstd >=1.5.5,<1.5.6.0a0
    - zstd >=1.5.5,<1.6.0a0
test:
  commands:
    - pip check
  imports:
    - zstandard
  requires:
    - pip
about:
  description: 'This project provides Python bindings for interfacing with the

    Zstandard compression library. A C extension and CFFI interface are

    provided.

    '
  dev_url: https://github.com/indygreg/python-zstandard
  doc_url: https://github.com/indygreg/python-zstandard/blob/main/README.rst#python-zstandard
  home: https://github.com/indygreg/python-zstandard
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - zstd/LICENSE
  summary: Zstandard bindings for Python
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: e4419183-aeb6-413c-b984-157eb5b91bb7
  recipe-maintainers:
    - rmax
    - xhochy
  remote_url: git@github.com:AnacondaRecipes/zstandard-feedstock.git
  sha: 7c3c99dbf4292646c54466c77e56eea9b0073cf9
