# This file created by conda-build 24.3.0
# meta.yaml template originally from:
# C:\b\abs_5f3aywj55d\clone\recipe, last modified Thu May  2 21:15:08 2024
# ------------------------------------------------

package:
  name: reproc
  version: 14.2.4
source:
  - patches: null
    sha256: 55c780f7faa5c8cabd83ebbb84b68e5e0e09732de70a129f6b3c801e905415dd
    url: https://github.com/DaanDeMeyer/reproc/archive/v14.2.4.tar.gz
build:
  number: '2'
  run_exports:
    - reproc >=14.2,<15.0a0
  string: hd77b12b_2
requirements:
  build:
    - bzip2 1.0.8 h2bbff1b_6
    - ca-certificates 2024.3.11 haa95532_0
    - cmake 3.26.4 h693b641_0
    - expat 2.6.2 hd77b12b_0
    - libffi 3.4.4 hd77b12b_1
    - libuv 1.44.2 h2bbff1b_0
    - lz4-c 1.9.4 h2bbff1b_1
    - ninja 1.10.2 haa95532_5
    - ninja-base 1.10.2 h6d14046_5
    - openssl 3.0.13 h2bbff1b_1
    - python 3.12.3 h1d929f7_0
    - sqlite 3.45.3 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2024a h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
    - xz 5.4.6 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_1
    - zstd 1.5.5 hd43e919_1
  host:
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
  run:
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
about:
  dev_url: https://github.com/DaanDeMeyer/reproc
  doc_src_url: https://github.com/DaanDeMeyer/reproc
  doc_url: https://github.com/DaanDeMeyer/reproc#reproc
  home: https://github.com/DaanDeMeyer/reproc
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: reproc (Redirected Process) is a cross-platform C/C++ library that simplifies
    starting, stopping and communicating with external programs.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 5f71191f-d48f-400b-8aee-11939464bcc3
  recipe-maintainers:
    - DaanDeMeyer
    - wolfv
  remote_url: git@github.com:AnacondaRecipes/reproc-feedstock.git
  sha: 39002db99a2955d830945b69264da997a7bf10aa
