# This file created by conda-build 24.3.0
# meta.yaml template originally from:
# C:\b\abs_97lgskwerx\clone\recipe, last modified Thu May  2 16:45:12 2024
# ------------------------------------------------

package:
  name: cryptography
  version: 42.0.5
source:
  sha256: 6fe07eec95dfd477eb9530aef5bead34fec819b3aaf6c5bd6d20565da607bfe1
  url: https://pypi.io/packages/source/c/cryptography/cryptography-42.0.5.tar.gz
build:
  number: '1'
  script:
    - set OPENSSL_DIR=%LIBRARY_PREFIX%
    - C:\\b\\abs_97lgskwerx\\croot\\cryptography_1714664736250\\_h_env\\python.exe
      -m pip install . -vv --no-deps --no-build-isolation
  string: py312h89fc84f_1
requirements:
  build:
    - rust 1.71.1 haa95532_0
    - rust_win-64 1.71.1 hd77b12b_0
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
  host:
    - bzip2 1.0.8 h2bbff1b_6
    - ca-certificates 2024.3.11 haa95532_0
    - cffi 1.15.1 py312h2bbff1b_3
    - expat 2.6.2 hd77b12b_0
    - libffi 3.4.4 hd77b12b_1
    - openssl 3.0.13 h2bbff1b_1
    - pip 23.3.1 py312haa95532_0
    - pycparser 2.21 pyhd3eb1b0_0
    - python 3.12.3 h1d929f7_0
    - semantic_version 2.8.5 pyhd3eb1b0_0
    - setuptools 68.2.2 py312haa95532_0
    - setuptools-rust 1.9.0 py312haa95532_0
    - sqlite 3.45.3 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2024a h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.41.2 py312haa95532_0
    - xz 5.4.6 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_1
  run:
    - cffi >=1.12
    - openssl >=3.0.13,<4.0a0
    - python >=3.12,<3.13.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - pip check
    - pytest -n auto
  requires:
    - certifi
    - cryptography-vectors 42.0.5.*
    - pip
    - pretend
    - pytest >=6.2.0
    - pytest-benchmark
    - pytest-cov
    - pytest-xdist
  source_files:
    - pyproject.toml
    - tests
about:
  description: 'Cryptography is a package which provides cryptographic recipes and

    primitives to Python developers. Our goal is for it to be your

    "cryptographic standard library". It supports Python 3.6+ and PyPy3 7.2+.

    cryptography includes both high level recipes and low level interfaces to

    common cryptographic algorithms such as symmetric ciphers, message digests,

    and key derivation functions.

    '
  dev_url: https://github.com/pyca/cryptography
  doc_url: https://cryptography.io/
  home: https://github.com/pyca/cryptography
  license: Apache-2.0 OR BSD-3-Clause
  license_family: OTHER
  license_file:
    - LICENSE
    - LICENSE.APACHE
    - LICENSE.BSD
  summary: Provides cryptographic recipes and primitives to Python developers
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 97f5ab6a-0575-4514-97c8-5270fe212036
  recipe-maintainers:
    - chenghlee
    - jakirkham
    - ocefpaf
  remote_url: git@github.com:AnacondaRecipes/cryptography-feedstock.git
  sha: 0bb377d45205a9b6b701fe70abcaa2c8dd3d585e
