# This file created by conda-build 24.3.0
# meta.yaml template originally from:
# C:\b\abs_9cepyauck5\clone\recipe, last modified Mon May  6 20:58:09 2024
# ------------------------------------------------

package:
  name: setuptools
  version: 69.5.1
source:
  patches:
    - patches/0002-disable-downloads-inside-conda-build.patch
    - patches/0021-Add-d1trimfile-SRC_DIR-to-make-pdbs-more-relocatable.patch
  sha256: 6c1fccdac05a97e598fb0ae3bbed5904ccb317337a51139dcd51453611bbb987
  url: https://pypi.io/packages/source/s/setuptools/setuptools-69.5.1.tar.gz
build:
  number: '0'
  string: py312haa95532_0
requirements:
  build:
    - m2-msys2-runtime 2.5.0.17080.65c939c 3
    - m2-patch 2.7.5 2
    - msys2-conda-epoch 20160418 1
  host:
    - bzip2 1.0.8 h2bbff1b_6
    - ca-certificates 2024.3.11 haa95532_0
    - expat 2.6.2 hd77b12b_0
    - libffi 3.4.4 hd77b12b_1
    - openssl 3.0.13 h2bbff1b_1
    - python 3.12.3 h1d929f7_0
    - sqlite 3.45.3 h2bbff1b_0
    - tk 8.6.14 h0416ee5_0
    - tzdata 2024a h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - xz 5.4.6 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_1
  run:
    - python >=3.12,<3.13.0a0
test:
  commands:
    - pip check
  imports:
    - pkg_resources
    - setuptools
  requires:
    - pip
about:
  description: 'Setuptools is a fully-featured, actively-maintained, and stable library

    designed to facilitate packaging Python projects.

    '
  dev_url: https://github.com/pypa/setuptools
  doc_url: https://setuptools.pypa.io
  home: https://github.com/pypa/setuptools
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Download, build, install, upgrade, and uninstall Python packages
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 9c92cd6b-5423-425d-af5a-b53ff17ec31e
  recipe-maintainers:
    - isuruf
    - jakirkham
    - msarahan
    - nicoddemus
    - ocefpaf
  remote_url: git@github.com:AnacondaRecipes/setuptools-feedstock.git
  sha: 5a6d059dfd9ffdedf41c08d03e2ac90821259dc9
  skip-lints:
    - missing_python_build_tool
    - missing_wheel
