version: '3'
services:
  server1:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "5001:5000"

  server2:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "5002:5000"

  server3:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "5003:5000"

  load_balancer:
    build:
      context: .
      dockerfile: load_balancer.Dockerfile
    ports:
      - "4001:4001"
    depends_on:
      - server1
      - server2
      - server3
