# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install Flask and requests
RUN pip install Flask requests

# Expose port 5000
EXPOSE 5000

# Run load_balancer.py when the container launches
CMD ["python", "load_balancer.py"]


