# This file created by conda-build 24.3.0
# meta.yaml template originally from:
# C:\b\abs_aed4997bno\clone\recipe, last modified Fri Apr 19 13:49:45 2024
# ------------------------------------------------

package:
  name: expat
  version: 2.6.2
source:
  sha256: 9c7c1b5dcbc3c237c500a8fb1493e14d9582146dd9b42aa8d3ffb856a3b927e0
  url: https://github.com/libexpat/libexpat/releases/download/R_2_6_2/expat-2.6.2.tar.bz2
build:
  number: '0'
  run_exports:
    - expat >=2.6.2,<3.0a0
  string: hd77b12b_0
requirements:
  build:
    - bzip2 1.0.8 h2bbff1b_5
    - cmake 3.26.4 h693b641_0
    - libuv 1.44.2 h2bbff1b_0
    - lz4-c 1.9.4 h2bbff1b_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
    - xz 5.4.6 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
    - zstd 1.5.5 hd43e919_0
  host:
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
  run:
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - xmlwf -h
about:
  description: 'Expat is a stream-oriented XML parser library written in C.

    Expat excels with files too large to fit RAM, and where performance

    and flexibility are crucial.

    '
  dev_url: https://github.com/libexpat/libexpat
  doc_url: https://libexpat.github.io/doc/
  home: https://libexpat.github.io
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Expat XML parser library in C
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: ae812eb1-85b8-48e0-be82-95dbe4d786a2
  recipe-maintainers:
    - kwilcox
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
    - scopatz
  remote_url: git@github.com:AnacondaRecipes/expat-feedstock.git
  sha: 6e0bb5339b147f22a33111361c1018ab2c57c36f
