# This file created by conda-build 24.3.0
# meta.yaml template originally from:
# C:\b\abs_aad84bnnw5\clone\recipe, last modified Mon Apr 29 14:54:34 2024
# ------------------------------------------------

package:
  name: idna
  version: '3.7'
source:
  sha256: 028ff3aadf0609c1fd278d8ea3089299412a7a8b9bd005dd08b9f8285bcb5cfc
  url: https://pypi.io/packages/source/i/idna/idna-3.7.tar.gz
build:
  number: '0'
  script: C:\\b\\abs_aad84bnnw5\\croot\\idna_1714398896795\\_h_env\\python.exe -m
    pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir
    -vv
  string: py312haa95532_0
requirements:
  host:
    - bzip2 1.0.8 h2bbff1b_5
    - ca-certificates 2024.3.11 haa95532_0
    - expat 2.6.2 hd77b12b_0
    - flit-core 3.9.0 py312he100be2_1
    - libffi 3.4.4 hd77b12b_0
    - openssl 3.0.13 h2bbff1b_0
    - pip 23.3.1 py312haa95532_0
    - python 3.12.3 h1d929f7_0
    - setuptools 68.2.2 py312haa95532_0
    - sqlite 3.41.2 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2024a h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.41.2 py312haa95532_0
    - xz 5.4.6 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
  run:
    - python >=3.12,<3.13.0a0
test:
  commands:
    - pip check
  imports:
    - idna
    - idna.codec
    - idna.compat
    - idna.core
  requires:
    - pip
about:
  description: 'A library to support the Internationalised Domain Names in Applications

    (IDNA) protocol as specified in RFC 5891. This version of the protocol

    is often referred to as "IDNA2008".

    '
  dev_url: https://github.com/kjd/idna
  doc_url: https://github.com/kjd/idna/blob/master/README.rst
  home: https://github.com/kjd/idna
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: Internationalized Domain Names in Applications (IDNA).
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: aa5638bc-773b-4760-a82c-0cbe8037b774
  recipe-maintainers:
    - goanpeca
    - jschueller
  remote_url: git@github.com:AnacondaRecipes/idna-feedstock.git
  sha: 4eba6abb2b9cac8c230c3d9f094b26caec847125
