# This file created by conda-build 24.3.0
# ------------------------------------------------

package:
  name: libsolv
  version: 0.7.24
source:
  patches:
    - conda_variant_priorization.patch
    - no_error_subdir_mismatch.patch
    - pcre2-compat.patch
    - win_export_and_static_build.patch
  sha256: 62743265222a729c7fe94c40f7b90ccc1ac5568f5ee6df46884e7ce3c16c78c7
  url: https://github.com/openSUSE/libsolv/archive/0.7.24.tar.gz
build:
  ignore_run_exports:
    - zlib
  noarch: false
  noarch_python: false
  number: '1'
  script: install_dynamic.bat
  string: h23ce68f_1
requirements:
  build:
    - bzip2 1.0.8 h2bbff1b_5
    - ca-certificates 2024.3.11 haa95532_0
    - cmake 3.26.4 h693b641_0
    - expat 2.6.2 hd77b12b_0
    - libffi 3.4.4 hd77b12b_0
    - libuv 1.44.2 h2bbff1b_0
    - lz4-c 1.9.4 h2bbff1b_0
    - ninja 1.10.2 haa95532_5
    - ninja-base 1.10.2 h6d14046_5
    - openssl 3.0.13 h2bbff1b_0
    - python 3.12.3 h1d929f7_0
    - sqlite 3.41.2 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2024a h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
    - xz 5.4.6 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
    - zstd 1.5.5 hd43e919_0
  host:
    - bzip2 1.0.8 h2bbff1b_5
    - ca-certificates 2024.3.11 haa95532_0
    - expat 2.6.2 hd77b12b_0
    - glib 2.78.4 hd77b12b_0
    - glib-tools 2.78.4 hd77b12b_0
    - libffi 3.4.4 hd77b12b_0
    - libglib 2.78.4 ha17d25a_0
    - libiconv 1.16 h2bbff1b_2
    - openssl 3.0.13 h2bbff1b_0
    - pcre2 10.42 h0ff8eda_0
    - pkg-config 0.29.2 h8cc25b3_0
    - python 3.12.3 h1d929f7_0
    - sqlite 3.41.2 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2024a h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - xz 5.4.6 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
  run:
    - pcre2 >=10.42,<10.43.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - if not exist %LIBRARY_INC%\solv\repo.h (exit 1)
    - if not exist %LIBRARY_BIN%\solv.dll (exit 1)
    - if not exist %LIBRARY_LIB%\solv.lib (exit 1)
    - if not exist %LIBRARY_BIN%\solvext.dll (exit 1)
    - if not exist %LIBRARY_LIB%\solvext.lib (exit 1)
    - if exist %LIBRARY_LIB%\solv_static.lib (exit 1)
    - if exist %LIBRARY_LIB%\solvext_static.lib (exit 1)
    - dumpsolv.exe -h
about:
  description: 'libsolv, a free package dependency solver using a satisfiability algorithm.

    '
  dev_url: https://github.com/openSUSE/libsolv
  doc_url: https://github.com/openSUSE/libsolv/tree/master/doc
  home: https://github.com/openSUSE/libsolv
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.BSD
  summary: Library for solving packages and reading repositories
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: fa61dfcd-a4f1-4c8e-a078-ff89748fb896
  recipe-maintainers:
    - JohanMabille
    - SylvainCorlay
    - adriendelsalle
    - davidbrochart
    - wolfv
  remote_url: git@github.com:AnacondaRecipes/libsolv-feedstock.git
  sha: 5c95f2e772e6082682ca6b3d68b33fca382c991d
