# This file created by conda-build 24.3.0
# meta.yaml template originally from:
# C:\b\abs_bdfatn_wzf\clone\recipe, last modified Tue Apr 30 14:19:40 2024
# ------------------------------------------------

package:
  name: conda-content-trust
  version: 0.2.0
source:
  fn: conda-content-trust-0.2.0.tar.gz
  sha256: ded769f69a0491bd1e002ce949a332ae5a47a60ce733adb8a724802c8fdfe02b
  url: https://github.com/conda/conda-content-trust/archive/0.2.0.tar.gz
build:
  entry_points:
    - conda-content-trust = conda_content_trust.cli:cli
  number: '1'
  script: C:\\b\\abs_bdfatn_wzf\\croot\\conda-content-trust_1714483201909\\_h_env\\python.exe
    -m pip install . -vv --no-deps --no-build-isolation
  string: py312haa95532_1
requirements:
  host:
    - bzip2 1.0.8 h2bbff1b_5
    - ca-certificates 2024.3.11 haa95532_0
    - editables 0.3 py312haa95532_0
    - expat 2.6.2 hd77b12b_0
    - hatch-vcs 0.3.0 py312haa95532_1
    - hatchling 1.21.1 py312haa95532_0
    - libffi 3.4.4 hd77b12b_0
    - openssl 3.0.13 h2bbff1b_0
    - packaging 23.2 py312haa95532_0
    - pathspec 0.10.3 py312haa95532_0
    - pip 23.3.1 py312haa95532_0
    - pluggy 1.0.0 py312haa95532_1
    - python 3.12.3 h1d929f7_0
    - setuptools 68.2.2 py312haa95532_0
    - setuptools-scm 8.0.4 py312haa95532_0
    - sqlite 3.41.2 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - trove-classifiers 2023.10.18 py312haa95532_0
    - typing-extensions 4.9.0 py312haa95532_1
    - typing_extensions 4.9.0 py312haa95532_1
    - tzdata 2024a h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.41.2 py312haa95532_0
    - xz 5.4.6 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
  run:
    - cryptography >=41
    - python >=3.12,<3.13.0a0
test:
  commands:
    - pip check
    - conda-content-trust --help
  imports:
    - conda_content_trust
    - conda_content_trust.authentication
    - conda_content_trust.common
    - conda_content_trust.root_signing
    - conda_content_trust.signing
  requires:
    - pip
about:
  dev_url: https://github.com/conda/conda-content-trust
  doc_url: https://github.com/conda/conda-content-trust/blob/main/README.md
  home: https://github.com/conda/conda-content-trust
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Signing and verification tools for conda
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: bd2e0fad-37d3-459b-91db-a01846fff07e
  remote_url: git@github.com:AnacondaRecipes/conda-content-trust-feedstock.git
  sha: c005730d88c9a0765982c3dcdff73ffecbf7fafe
