# This file created by conda-build 24.3.0
# meta.yaml template originally from:
# C:\b\abs_2biq999z4b\clone\recipe, last modified Thu May  9 14:31:12 2024
# ------------------------------------------------

package:
  name: libssh2
  version: 1.11.0
source:
  sha256: 3736161e41e2693324deb38c26cfdc3efe6209d634ba4258db1cecff6a5ad461
  url: https://www.libssh2.org/download/libssh2-1.11.0.tar.gz
build:
  number: '0'
  run_exports:
    - libssh2 >=1.11.0,<2.0a0
  string: h291bd65_0
requirements:
  build:
    - cmake-no-system 3.25.3 h6c2663c_0
    - ninja-base 1.10.2 h6d14046_5
    - vs2015_runtime 14.27.29016 h5e58377_2
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
  host:
    - ca-certificates 2024.3.11 haa95532_0
    - openssl 3.0.13 h2bbff1b_1
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - zlib 1.2.13 h8cc25b3_1
  run:
    - openssl >=3.0.13,<4.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
    - zlib >=1.2.13,<1.3.0a0
test:
  commands:
    - if not exist %LIBRARY_INC%\\libssh2.h exit 1
    - if not exist %LIBRARY_INC%\\libssh2_publickey.h exit 1
    - if not exist %LIBRARY_INC%\\libssh2_sftp.h exit 1
    - if not exist %LIBRARY_LIB%\\libssh2.lib exit 1
    - if not exist %LIBRARY_LIB%\\pkgconfig\\libssh2.pc exit 1
    - if not exist %LIBRARY_BIN%\\libssh2.dll exit 1
about:
  description: 'libssh2 is a library implementing the SSH2 protocol, available under
    the revised BSD license.

    '
  dev_url: https://github.com/libssh2/libssh2
  doc_url: https://www.libssh2.org/docs.html
  home: https://www.libssh2.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: the SSH library
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 2b00af0d-4543-49a6-9c0b-557a40251d2e
  recipe-maintainers:
    - shadowwalkersb
  remote_url: git@github.com:AnacondaRecipes/libssh2-feedstock.git
  sha: 6d9e2b17f5ba2af3960e4e7b8ae32f53f6fadf52
