# This file created by conda-build 3.28.0
# meta.yaml template originally from:
# C:\Users\dev-admin\perseverance-python-buildout\aggregate\truststore-feedstock\recipe, last modified Tue Dec  5 16:46:32 2023
# ------------------------------------------------

package:
  name: truststore
  version: 0.8.0
source:
  fn: truststore-0.8.0.tar.gz
  sha256: c862292f8d136bfcf2a7827a1fd1c1b27944a982741205fb466005673b570df8
  url: https://github.com/sethmlarson/truststore/archive/refs/tags/v0.8.0.tar.gz
build:
  number: '0'
  script: C:\\Users\\dev-admin\\perseverance-python-buildout\\croot\\truststore_1701881385424\\_h_env\\python.exe
    -m pip install . -vv --no-deps --no-build-isolation
  string: py312haa95532_0
requirements:
  host:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.08.22 haa95532_0
    - expat 2.5.0 hd77b12b_0
    - flit-core 3.9.0 py312h7146dc4_0
    - libffi 3.4.4 hd77b12b_0
    - openssl 3.0.12 h2bbff1b_0
    - pip 23.3.1 py312haa95532_0
    - python 3.12.0 h1d929f7_0
    - setuptools 68.0.0 py312haa95532_0
    - sqlite 3.41.2 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2023c h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.41.2 py312haa95532_0
    - xz 5.4.5 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
  run:
    - python >=3.12,<3.13.0a0
test:
  commands:
    - pip check
    - pytest -v -s -rs --no-flaky-report --max-runs=3 tests/
  imports:
    - truststore
  requires:
    - aiohttp
    - flaky
    - httpx
    - pip
    - pyopenssl
    - pytest
    - pytest-asyncio
    - pytest-httpserver
    - requests
    - trustme
    - urllib3
  source_files:
    - tests
about:
  description: "A library which exposes native system certificate stores (ie \u201C\
    trust stores\u201D)\nthrough an ssl.SSLContext-like API. This means that Python\
    \ applications no\nlonger need to rely on certifi as a root certificate store.\n"
  dev_url: https://github.com/sethmlarson/truststore
  doc_url: https://truststore.readthedocs.io/
  home: https://github.com/sethmlarson/truststore
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Verify certificates using native system trust stores
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - wolfv
