# This file created by conda-build 24.3.0
# meta.yaml template originally from:
# C:\b\abs_2alamqss6p\clone\recipe, last modified Mon Apr 15 16:27:43 2024
# ------------------------------------------------

package:
  name: frozendict
  version: 2.4.2
source:
  fn: frozendict-2.4.2.tar.gz
  sha256: 741779e1d1a2e6bb2c623f78423bd5d14aad35dc0c57e6ccc89e54eaab5f1b8a
  url: https://pypi.org/packages/source/f/frozendict/frozendict-2.4.2.tar.gz
build:
  number: '0'
  script: python -m pip install . --no-deps --no-build-isolation -v
  script_env:
    - FROZENDICT_PURE_PY=1
  string: py312haa95532_0
requirements:
  build: []
  host:
    - bzip2 1.0.8 h2bbff1b_5
    - ca-certificates 2024.3.11 haa95532_0
    - expat 2.5.0 hd77b12b_0
    - libffi 3.4.4 hd77b12b_0
    - openssl 3.0.13 h2bbff1b_0
    - pip 23.3.1 py312haa95532_0
    - python 3.12.2 h1d929f7_0
    - setuptools 68.2.2 py312haa95532_0
    - sqlite 3.41.2 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2024a h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.41.2 py312haa95532_0
    - xz 5.4.6 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
  run:
    - python >=3.12,<3.13.0a0
test:
  commands:
    - pip check
    - pytest -v test
  imports:
    - frozendict
  requires:
    - pip
    - pytest
  source_files:
    - test
about:
  description: frozendict is a simple immutable dictionary. It's fast as dict, and
    sometimes faster!
  dev_url: https://github.com/Marco-Sulla/python-frozendict
  doc_url: https://github.com/Marco-Sulla/python-frozendict
  home: https://github.com/Marco-Sulla/python-frozendict
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE.txt
  summary: An immutable dictionary
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 2ad72b6f-3a18-4932-907f-fe065d1fe700
  recipe-maintainers:
    - Marco-Sulla
    - ltalirz
  remote_url: git@github.com:AnacondaRecipes/frozendict-feedstock.git
  sha: 5db9edb14d67c968539db5bba840f7ecbd7fc5d4
