# This file created by conda-build 24.3.0
# meta.yaml template originally from:
# C:\b\abs_71xr36ua5r\clone\recipe, last modified Tue Apr 30 15:44:17 2024
# ------------------------------------------------

package:
  name: distro
  version: 1.9.0
source:
  fn: distro-1.9.0.tar.gz
  sha256: 2fa77c6fd8940f116ee1d6b94a2f90b13b5ea8d019b98bc8bafdcabcdd9bdbed
  url: https://pypi.io/packages/source/d/distro/distro-1.9.0.tar.gz
build:
  entry_points:
    - distro = distro.distro:main
  number: '0'
  script: C:\\b\\abs_71xr36ua5r\\croot\\distro_1714488282676\\_h_env\\python.exe -m
    pip install . --no-deps --ignore-installed --no-cache-dir -v --no-build-isolation
  string: py312haa95532_0
requirements:
  host:
    - bzip2 1.0.8 h2bbff1b_5
    - ca-certificates 2024.3.11 haa95532_0
    - expat 2.6.2 hd77b12b_0
    - libffi 3.4.4 hd77b12b_1
    - openssl 3.0.13 h2bbff1b_0
    - pip 23.3.1 py312haa95532_0
    - python 3.12.3 h1d929f7_0
    - setuptools 68.2.2 py312haa95532_0
    - sqlite 3.41.2 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2024a h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.41.2 py312haa95532_0
    - xz 5.4.6 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
  run:
    - python >=3.12,<3.13.0a0
test:
  commands:
    - pip check
    - distro --help
  imports:
    - distro
  requires:
    - pip
about:
  description: distro provides information about the OS distribution it runs on, such
    as a reliable machine-readable ID, or version information.
  dev_url: https://github.com/python-distro/distro
  doc_url: https://distro.readthedocs.io
  home: https://github.com/python-distro/distro
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A much more elaborate replacement for removed Python's 'platform.linux_distribution()'
    method
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 7182e51d-7ecd-4ca7-89bf-528a10b0040e
  recipe-maintainers:
    - abloemert
    - windelbouwman
  remote_url: git@github.com:AnacondaRecipes/distro-feedstock.git
  sha: f461cfeda5a73c272756cce6e91d26353b39a0f9
