# This file created by conda-build 3.28.0
# meta.yaml template originally from:
# C:\Users\dev-admin\perseverance-python-buildout\aggregate\platformdirs-feedstock\recipe, last modified Tue Dec  5 16:44:44 2023
# ------------------------------------------------

package:
  name: platformdirs
  version: 3.10.0
source:
  sha256: b45696dab2d7cc691a3226759c0d3b00c47c8b6e293d96f6436f733303f77f6d
  url: https://pypi.io/packages/source/p/platformdirs/platformdirs-3.10.0.tar.gz
build:
  number: '0'
  script: C:\\Users\\dev-admin\\perseverance-python-buildout\\croot\\platformdirs_1701797392447\\_h_env\\python.exe
    -m pip install . --no-deps --no-build-isolation -vv
  string: py312haa95532_0
requirements:
  host:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.08.22 haa95532_0
    - editables 0.3 py312haa95532_0
    - expat 2.5.0 hd77b12b_0
    - hatch-vcs 0.3.0 py312haa95532_1
    - hatchling 1.18.0 py312haa95532_1
    - libffi 3.4.4 hd77b12b_0
    - openssl 3.0.12 h2bbff1b_0
    - packaging 23.1 py312haa95532_0
    - pathspec 0.10.3 py312haa95532_0
    - pip 23.3.1 py312haa95532_0
    - pluggy 1.0.0 py312haa95532_1
    - python 3.12.0 h1d929f7_0
    - setuptools 68.0.0 py312haa95532_0
    - setuptools-scm 7.1.0 py312haa95532_1
    - sqlite 3.41.2 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - trove-classifiers 2023.10.18 py312haa95532_0
    - typing-extensions 4.7.1 py312haa95532_0
    - typing_extensions 4.7.1 py312haa95532_0
    - tzdata 2023c h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.41.2 py312haa95532_0
    - xz 5.4.5 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
  run:
    - python >=3.12,<3.13.0a0
test:
  commands:
    - pip check
    - pytest tests -vv
  imports:
    - platformdirs
  requires:
    - appdirs
    - pip
    - pytest
    - pytest-mock
  source_files:
    - tests
about:
  description: 'About A small Python module for determining appropriate

    platform-specific dirs, e.g. a "user data dir".

    '
  dev_url: https://github.com/platformdirs/platformdirs
  doc_url: https://platformdirs.readthedocs.io/
  home: https://github.com/platformdirs/platformdirs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A small Python module for determining appropriate platform-specific dirs,
    e.g. a "user data dir".
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - adament
    - gaborbernat
