# This file created by conda-build 24.3.0
# meta.yaml template originally from:
# C:\b\abs_4fdm88t7zi\clone\recipe, last modified Tue Apr 30 14:32:32 2024
# ------------------------------------------------

package:
  name: jsonpatch
  version: '1.33'
source:
  sha256: 9fcd4009c41e6d12348b4a0ff2563ba56a2923a7dfee731d004e212e1ee5030c
  url: https://pypi.io/packages/source/j/jsonpatch/jsonpatch-1.33.tar.gz
build:
  number: '1'
  script: C:\\b\\abs_4fdm88t7zi\\croot\\jsonpatch_1714483974578\\_h_env\\python.exe
    -m pip install . --no-deps --no-build-isolation -vv
  string: py312haa95532_1
requirements:
  host:
    - bzip2 1.0.8 h2bbff1b_5
    - ca-certificates 2024.3.11 haa95532_0
    - expat 2.6.2 hd77b12b_0
    - libffi 3.4.4 hd77b12b_0
    - openssl 3.0.13 h2bbff1b_0
    - pip 23.3.1 py312haa95532_0
    - python 3.12.3 h1d929f7_0
    - setuptools 68.2.2 py312haa95532_0
    - sqlite 3.41.2 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2024a h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.41.2 py312haa95532_0
    - xz 5.4.6 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
  run:
    - jsonpointer >=1.9
    - python >=3.12,<3.13.0a0
test:
  commands:
    - pip check
    - pytest tests.py
  imports:
    - jsonpatch
  requires:
    - pip
    - pytest
  source_files:
    - tests.*
about:
  description: 'python-json-patch is a Python library for applying JSON patches (RFC
    6902).

    Python 2.7 and 3.4+ are supported. Tests are run on both CPython and PyPy.

    '
  dev_url: https://github.com/stefankoegl/python-json-patch
  doc_url: https://python-json-patch.readthedocs.io
  home: https://github.com/stefankoegl/python-json-patch
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Apply JSON-Patches (RFC 6902)
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 4f2575fa-0a26-47b9-bf6f-21afb4ea0e2d
  recipe-maintainers:
    - anguslees
    - pavelzw
    - pmlandwehr
  remote_url: git@github.com:AnacondaRecipes/jsonpatch-feedstock.git
  sha: 65c0212085ccd2a1c3f7bb70147eacab8b594bf6
