#!/bin/sh
_CONDA_ROOT="C:\b\abs_f3egtzumcq\croot\conda_1715635886039\_h_env"
# Copyright (C) 2012 Anaconda, Inc
# SPDX-License-Identifier: BSD-3-Clause
\. "$_CONDA_ROOT/etc/profile.d/conda.sh" || return $?
conda activate "$@"
