# This file created by conda-build 3.27.0
# meta.yaml template originally from:
# C:\Users\dev-admin\perseverance-python-buildout\aggregate\colorama-feedstock\recipe, last modified Wed Nov  8 19:25:23 2023
# ------------------------------------------------

package:
  name: colorama
  version: 0.4.6
source:
  sha256: 08695f5cb7ed6e0531a20572697297273c47b8cae5a63ffc6d6ed5c201be6e44
  url: https://pypi.io/packages/source/c/colorama/colorama-0.4.6.tar.gz
build:
  number: '0'
  script: C:\\Users\\dev-admin\\perseverance-python-buildout\\croot\\colorama_1699472650914\\_h_env\\python.exe
    -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  string: py312haa95532_0
requirements:
  host:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.08.22 haa95532_0
    - editables 0.3 py312haa95532_0
    - expat 2.5.0 hd77b12b_0
    - hatchling 1.18.0 py312haa95532_0
    - libffi 3.4.4 hd77b12b_0
    - openssl 3.0.12 h2bbff1b_0
    - packaging 23.1 py312haa95532_0
    - pathspec 0.10.3 py312haa95532_0
    - pip 23.3 py312haa95532_0
    - pluggy 1.0.0 py312haa95532_1
    - python 3.12.0 h1d929f7_0
    - setuptools 68.0.0 py312haa95532_0
    - sqlite 3.41.2 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - trove-classifiers 2023.10.18 py312haa95532_0
    - tzdata 2023c h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.41.2 py312haa95532_0
    - xz 5.4.2 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
  run:
    - python >=3.12,<3.13.0a0
test:
  commands:
    - pip check
  imports:
    - colorama
  requires:
    - pip
about:
  description: 'colorama is a cross-platform colored terminal text.It makes

    ANSI escape character sequences (for producing colored terminal text

    and cursor positioning) work under MS Windows.

    '
  dev_url: https://github.com/tartley/colorama
  doc_url: https://pypi.org/project/colorama/
  home: https://github.com/tartley/colorama
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Cross-platform colored terminal text
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - kwilcox
    - ocefpaf
