# This file created by conda-build 24.5.1
# meta.yaml template originally from:
# C:\b\abs_7a8c0lyh9x\clone\recipe, last modified Fri Jun 21 21:09:42 2024
# ------------------------------------------------

package:
  name: powershell_shortcut_miniconda
  version: 0.0.1
build:
  number: '2'
  string: haa95532_2
requirements:
  build: []
  run:
    - python
  run_constrained:
    - anaconda-navigator >=1.9.8
app:
  entry: start powershell.exe -ExecutionPolicy ByPass -NoExit -Command  "& '{CONDA_ROOT_PREFIX}\\shell\\condabin\\conda-hook.ps1'
    ; conda activate '{CONDA_PREFIX}'"
  summary: Anaconda Powershell Prompt
  type: desk
about:
  license: BSD-3-Clause
  license_family: BSD
  summary: Powershell shortcut creator for Windows (using menuinst)
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 7a325945-a355-486f-aaa6-5eb0e6a6544b
  remote_url: git@github.com:AnacondaRecipes/powershell_shortcut_miniconda-feedstock.git
  sha: 92d100795c727bfc1565b2a9cba409deddaa6d1d
