# This file created by conda-build 24.3.0
# ------------------------------------------------

package:
  name: vc
  version: 14.2
build:
  number: 1
  string: h2eaa2aa_1
  track_features:
    - vc14
requirements:
  build: []
  run:
    - vs2015_runtime >=14.29.30133
about:
  description: 'This metapackage is used to enforce consistency of runtime

    dependencies within an environment

    '
  dev_url: https://github.com/conda/conda/wiki/VC-features
  doc_url: https://github.com/conda/conda/wiki/VC-features
  home: https://github.com/conda/conda/wiki/VC-features
  license: BSD-3-Clause
  license_family: BSD
  license_file: C:\b\abs_6fi_3ip7pq\clone\recipe/LICENSE
  summary: A meta-package to impose mutual exclusivity among software built with different
    VS versions
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 6fb09c9b-995f-45fb-aa79-e41f9bb018e9
  remote_url: git@github.com:AnacondaRecipes/vs2019-feedstock.git
  sha: aeb4fcf21dfbdf357acf8454d1c3ca08b0b6c173
