# This file created by conda-build 24.5.1
# meta.yaml template originally from:
# C:\b\abs_a7hvzm4y95\clone\recipe, last modified Thu Jun 20 20:44:11 2024
# ------------------------------------------------

package:
  name: urllib3
  version: 2.2.2
source:
  sha256: dd505485549a7a552833da5e6063639d0d177c04f23bc3864e41e5dc5f612168
  url: https://pypi.io/packages/source/u/urllib3/urllib3-2.2.2.tar.gz
build:
  number: '0'
  script: C:\\b\\abs_a7hvzm4y95\\croot\\urllib3_1718912661242\\_h_env\\python.exe
    -m pip install . --no-deps --no-build-isolation -vv
  string: py312haa95532_0
requirements:
  host:
    - bzip2 1.0.8 h2bbff1b_6
    - ca-certificates 2024.3.11 haa95532_0
    - editables 0.3 py312haa95532_0
    - expat 2.6.2 hd77b12b_0
    - hatchling 1.21.1 py312haa95532_0
    - libffi 3.4.4 hd77b12b_1
    - openssl 3.0.14 h827c3e9_0
    - packaging 23.2 py312haa95532_0
    - pathspec 0.10.3 py312haa95532_0
    - pip 24.0 py312haa95532_0
    - pluggy 1.0.0 py312haa95532_1
    - python 3.12.4 h14ffc60_1
    - setuptools 69.5.1 py312haa95532_0
    - sqlite 3.45.3 h2bbff1b_0
    - tk 8.6.14 h0416ee5_0
    - trove-classifiers 2023.10.18 py312haa95532_0
    - tzdata 2024a h04d1e81_0
    - vc 14.2 h2eaa2aa_1
    - vs2015_runtime 14.29.30133 h43f2093_3
    - wheel 0.43.0 py312haa95532_0
    - xz 5.4.6 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_1
  run:
    - brotli-python >=1.0.9
    - pysocks >=1.5.6,<2.0,!=1.5.7
    - python >=3.12,<3.13.0a0
  run_constrained:
    - h2 >=4,<5
    - requests >=2.26.0
    - selenium >=4.4.3
    - zstandard >=0.18.0
test:
  commands:
    - pip check
  imports:
    - urllib3
    - urllib3.contrib
    - urllib3.util
  requires:
    - pip
about:
  description: 'urllib3 is a powerful, sanity-friendly HTTP client for Python. Much
    of the

    Python ecosystem already uses urllib3. urllib3 brings many critical features

    that are missing from the Python standard libraries, such as thread safety,

    connection pooling, client side ssl/tls verification, support for gzip and

    deflate encodings, HTTP and SOCKS proxy support, helpers for retrying requests

    and dealing with HTTP redirects.

    '
  dev_url: https://github.com/urllib3/urllib3
  doc_url: https://urllib3.readthedocs.io/
  home: https://urllib3.readthedocs.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: HTTP library with thread-safe connection pooling, file post, and more.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: a74a2f2b-ad40-4487-9eef-cfbb55b87e23
  recipe-maintainers:
    - ocefpaf
    - pmlandwehr
    - sethmlarson
    - sigmavirus24
  remote_url: git@github.com:AnacondaRecipes/urllib3-feedstock.git
  sha: 089d347fd6e3f44a31d168a30c61868e4592109a
