# This file created by conda-build 24.5.0
# meta.yaml template originally from:
# C:\b\abs_a7h7n45ccq\clone\recipe, last modified Wed May 22 17:39:24 2024
# ------------------------------------------------

package:
  name: tqdm
  version: 4.66.4
source:
  sha256: e4d936c9de8727928f3be6079590e97d9abfe8d39a590be678eb5919ffc186bb
  url: https://pypi.io/packages/source/t/tqdm/tqdm-4.66.4.tar.gz
build:
  entry_points:
    - tqdm = tqdm.cli:main
  number: '0'
  script: C:\\b\\abs_a7h7n45ccq\\croot\\tqdm_1716395987133\\_h_env\\python.exe -m
    pip install . --no-deps --no-build-isolation -vv
  string: py312hfc267ef_0
requirements:
  host:
    - bzip2 1.0.8 h2bbff1b_6
    - ca-certificates 2024.3.11 haa95532_0
    - expat 2.6.2 hd77b12b_0
    - libffi 3.4.4 hd77b12b_1
    - openssl 3.0.13 h2bbff1b_2
    - packaging 23.2 py312haa95532_0
    - pip 24.0 py312haa95532_0
    - python 3.12.3 h1d929f7_1
    - setuptools 69.5.1 py312haa95532_0
    - setuptools-scm 8.0.4 py312haa95532_0
    - setuptools_scm 8.0.4 hd3eb1b0_0
    - sqlite 3.45.3 h2bbff1b_0
    - tk 8.6.14 h0416ee5_0
    - toml 0.10.2 pyhd3eb1b0_0
    - typing-extensions 4.11.0 py312haa95532_0
    - typing_extensions 4.11.0 py312haa95532_0
    - tzdata 2024a h04d1e81_0
    - vc 14.2 h2eaa2aa_1
    - vs2015_runtime 14.29.30133 h43f2093_3
    - wheel 0.43.0 py312haa95532_0
    - xz 5.4.6 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_1
  run:
    - colorama
    - python >=3.12,<3.13.0a0
  run_constrained:
    - ipywidgets >=6
test:
  commands:
    - pip check
    - tqdm --help
    - tqdm -v | rg 4.66.4
    - pytest -k "not tests_perf"
  imports:
    - tqdm
  requires:
    - dask-core
    - numpy
    - pandas
    - pip
    - pytest >=6
    - pytest-asyncio
    - pytest-timeout
    - pytest-xdist
    - rich
    - ripgrep
  source_files:
    - pyproject.toml
    - tests
about:
  description: A Fast, Extensible Progress Bar for Python and CLI
  dev_url: https://github.com/tqdm/tqdm
  doc_url: https://tqdm.github.io/
  home: https://tqdm.github.io/
  license: MPL-2.0 AND MIT
  license_family: MOZILLA
  license_file: LICENCE
  summary: A Fast, Extensible Progress Meter
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: a793aa66-aeca-45ae-9b69-e62cf13073a2
  recipe-maintainers:
    - casperdcl
    - pmlandwehr
  remote_url: git@github.com:AnacondaRecipes/tqdm-feedstock.git
  sha: c9393a18201f134324d8bd8196e2afda374bf895
