# This file created by conda-build 24.3.0
# ------------------------------------------------

package:
  name: yaml-cpp
  version: 0.8.0
source:
  sha256: fbe74bbdcee21d656715688706da3c8becfd946d92cd44705cc6098bb23b3a16
  url: https://github.com/jbeder/yaml-cpp/archive/refs/tags/0.8.0.tar.gz
build:
  number: 1
  run_exports:
    - yaml-cpp >=0.8.0,<0.9.0a0
  string: hd77b12b_1
requirements:
  build:
    - bzip2 1.0.8 h2bbff1b_5
    - ca-certificates 2024.3.11 haa95532_0
    - cmake 3.26.4 h693b641_0
    - expat 2.6.2 hd77b12b_0
    - libffi 3.4.4 hd77b12b_1
    - libuv 1.44.2 h2bbff1b_0
    - lz4-c 1.9.4 h2bbff1b_0
    - ninja 1.10.2 haa95532_5
    - ninja-base 1.10.2 h6d14046_5
    - openssl 3.0.13 h2bbff1b_0
    - python 3.12.3 h1d929f7_0
    - sqlite 3.45.3 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2024a h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
    - xz 5.4.6 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
    - zstd 1.5.5 hd43e919_0
  host:
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
  run:
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - if not exist %LIBRARY_BIN%\\yaml-cpp.dll exit 1
    - test/test.bat
  files:
    - test
  requires:
    - cmake
    - ninja
    - vs2017_win-64
about:
  description: yaml-cpp is a YAML parser and emitter in C++ matching the YAML 1.2
    spec.
  dev_url: https://github.com/jbeder/yaml-cpp
  doc_url: https://github.com/jbeder/yaml-cpp.wiki.git
  home: https://github.com/jbeder/yaml-cpp
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: yaml-cpp is a YAML parser and emitter in C++ matching the YAML 1.2 spec.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 1486ae24-11be-408a-90e4-e316854a5877
  recipe-maintainers:
    - allanleal
    - marcelotrevisani
    - seanyen
    - tadeu
    - wolfv
  remote_url: git@github.com:AnacondaRecipes/yaml-cpp-feedstock.git
  sha: beb9361a150f2a91c77bd0504cd052f49b0e3ad7
